### ISSUE TITLE
Sync/Project path

### ISSUE THREAD

**Issue by franz-josef-kaiser** [mattbanks/vagrant-dev-box#2]
Per default the `Vagrantfile` syncs to your personal Dropbox folder on your disk. Also the `~/Sites` directory isn't shipped with the repo.

Nice to have: `.idea` folder in `.gitignore` to hold PHPStorm files out of the repo.

**Comment by mattbanks** [comment]
Those are just the settings I use, you can fork it and change the paths to what works for you. I actually don't even use this anymore - I'll be adding some text to the readme and header saying it's deprecated soon.
